-- V1: extensions + enum types
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TYPE auth_provider AS ENUM ('PASSWORD','GOOGLE');
CREATE TYPE file_type AS ENUM ('PDF','DOCX','PPTX','XLSX','CSV','TXT','MD');
CREATE TYPE file_status AS ENUM ('UPLOADING','PARSING','EMBEDDING','READY','FAILED');
CREATE TYPE chat_scope AS ENUM ('REGULAR','FOLDER','CHANNEL');
CREATE TYPE channel_visibility AS ENUM ('PUBLIC','UNLISTED','PRIVATE');
CREATE TYPE membership_status AS ENUM ('PENDING','APPROVED','REJECTED','BANNED','LEFT');
CREATE TYPE message_role AS ENUM ('USER','ASSISTANT','SYSTEM');
